server:
  port: 5000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: app1-route
          uri: http://localhost:8081
          predicates:
            - Path=/app1/**
          filters:
            - StripPrefix=1