spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/job?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    druid:
      max-active: 10