server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:file:E:/data/localdb/h2;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    schema: classpath:schema.sql
    data: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true