server:
  port: 8100
spring:
  application:
    name: producer-server
  zipkin:
    base-url: http://localhost:9411/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
