server:
  port: 8080

spring:
  application:
    name: consul-demo
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        format: json
        enabled: true
        prefix: configuration
        defaultContext: apps
        profileSeparator: '::'
    discovery:
      tags: foo=bar, baz
