#
server:
  port: 8080

#spring:
#  redis:
#    host: localhost
#    port: 6379
#    password:
#    timeout: 3000

spring:
  redis:
#    host: localhost
#    port: 6379
#    password:
    timeout: 3000
    cluster:
      nodes: localhost:6379,localhost:6380,localhost:6381
