server:
  port: 9999
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: samples-order
management:
  endpoints:
    web:
      exposure:
        include: ["*"]
  metrics:
    tags:
      application: ${spring.application.name}
