server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aracwong/learn-root/tree/master/learn-springcloud/learn-springcloud-config/learn-springcloud-config-repository
#          search-paths: myconfigpath
          forcePull: true
      label: master
  application:
    name: config-server
management:
  security:
    enabled: false