server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: http://github.com/aracwong/config-repos.git
  application:
    name: config-server
management:
  security:
    enabled: false