server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/aracwong/config-server.git
#          search-paths: myconfigpath
          forcePull: true
      label: master
  application:
    name: config-server
management:
  security:
    enabled: false