server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/aracwong/config-server.git
          forcePull: true
#        default-application-name: application
      label: master
  application:
    name: config-server
management:
  security:
    enabled: false