nacos:
  config:
    server-addr: 127.0.0.1:8848
    auto-refresh: true
    data-id: nacos-demo
    group: adx
    namespace: 0cce6a6e-9de2-4fde-b913-890757d99071
    type: yaml
    max-retry: 10
    config-retry-time: 2000
    config-long-poll-timeout: 46000
    enable-remote-sync-config: true