nacos:
  config:
    server-addr: 127.0.0.1:8848
    auto-refresh: true
    data-id: nacos-demo
    group: adx
    namespace: 66112b45-b996-4a26-83e8-5c93165b1a3c
    type: yaml
    max-retry: 10
    config-retry-time: 2000
    config-long-poll-timeout: 46000
    enable-remote-sync-config: true