nacos:
  config:
    server-addr: 127.0.0.1:8848
    auto-refresh: true
    data-id: nacos-demo
    group: adx
    namespace: 6a635bba-1c80-4879-83f7-afe318f1ba06
    type: yaml
    max-retry: 10
    config-retry-time: 2000
    config-long-poll-timeout: 46000
    enable-remote-sync-config: true