security:
  oauth2:
    client:
      client-id: YWDsSkYdfMZKyGqAoW4R0xOO
      client-secret: RWIHz5dXmt3EAFrxkYQ3rvI6tbFp7Fvs
      access-token-uri: http://openapi.baidu.com/oauth/2.0/token
      user-authorization-uri: http://openapi.baidu.com/oauth/2.0/authorize
    resource:
      userInfoUri: https://openapi.baidu.com/rest/2.0/passport/users/getInfo